### ISSUE TITLE
Could you pick a license and add it to package.json?

### ISSUE THREAD

**Issue by silviapfeiffer** [dominictarr/assertions#6]
Sorry to be picky like this, but it would really help to have a license. Thanks!

**Comment by dominictarr** [comment]
fixed.
If you are using my old modules and you are wondering which licence they should have you may consider them to be MIT licensed. (also, you are welcome to post issues about it, but just so you know)

**Comment by dominictarr** [comment]
fixed in 2.3.4

**Comment by silviapfeiffer** [comment]
awesome, thanks!
